version: '3'

tasks:
  run:
    cmds:
      - go run github.com/franchb/htmgo/cli/htmgo/v2@latest run
    silent: true

  build:
    cmds:
      - go run github.com/franchb/htmgo/cli/htmgo/v2@latest build

  watch:
    cmds:
      - go run github.com/franchb/htmgo/cli/htmgo/v2@latest watch
    silent: true